# Generated by Django 4.0.5 on 2022-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_userbot_lastname_alter_userbot_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponserChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='Channel Username')),
            ],
        ),
    ]
